# Generated by Django 4.2 on 2023-06-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perros', '0005_perro_castrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vacuna', models.CharField(choices=[('vacunacion_antirrabica', 'Vacunación Antirrábica'), ('vacunacion_general', 'Vacunación General')], max_length=25)),
                ('dosis', models.CharField(blank=True, max_length=30)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros_vacunas', to='perros.perro')),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros_atenciones', to='perros.perro')),
            ],
        ),
    ]
