# Generated by Django 4.2 on 2023-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='vacuna',
            field=models.CharField(choices=[('vacunacion antirrabica', 'Vacunación Antirrábica'), ('vacunacion general', 'Vacunación General')], max_length=25),
        ),
    ]
