# Generated by Django 4.2 on 2023-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0002_alter_vacuna_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(choices=[('vacunación antirrábica', 'Vacunación Antirrábica'), ('vacunación general', 'Vacunación General'), ('castración', 'Castración'), ('consulta', 'Consulta general'), ('desparasitación', 'Desparasitación')], default='consulta', max_length=25),
        ),
    ]
