# Generated by Django 4.2 on 2023-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0003_atencion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(blank=True, choices=[('vacunación antirrábica', 'Vacunación Antirrábica'), ('vacunación general', 'Vacunación General'), ('castración', 'Castración'), ('consulta', 'Consulta general'), ('desparasitación', 'Desparasitación')], max_length=25),
        ),
    ]
