# Generated by Django 4.2 on 2023-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0005_alter_atencion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
