# Generated by Django 4.2 on 2023-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0006_alter_atencion_id_alter_vacuna_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='vacuna',
            field=models.CharField(choices=[('vacunación antirrábica', 'Vacunación Antirrábica'), ('vacunación general', 'Vacunación General')], max_length=25),
        ),
    ]
