# Generated by Django 4.2 on 2023-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0007_alter_vacuna_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(choices=[('castración', 'Castración'), ('consulta', 'Consulta general'), ('desparasitación', 'Desparasitación')], max_length=25),
        ),
    ]
