# Generated by Django 4.2 on 2023-05-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerroAdopcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'M'), ('HEMBRA', 'H'), ('-', 'Ns')], default='-', max_length=6)),
                ('color', models.CharField(default='', max_length=20, null=True)),
                ('edad', models.CharField(default='', max_length=20, null=True)),
                ('peso', models.CharField(default='', max_length=5, null=True)),
                ('contacto', models.CharField(default='', max_length=50, null=True)),
                ('altura', models.CharField(default='', max_length=5, null=True)),
                ('raza', models.CharField(default='', max_length=20, null=True)),
                ('historial_vacunacion', models.CharField(default='', max_length=500, null=True)),
                ('descripcion', models.CharField(default='', max_length=500, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_perro_adopcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
