# Generated by Django 4.2 on 2023-05-09 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perroadopcion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='perroadopcion',
            name='publicador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='publicador_perro_adopcion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
