# Generated by Django 4.2 on 2023-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_remove_perroadopcion_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroadopcion',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
    ]
