# Generated by Django 4.2 on 2023-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_perroadopcion_adoptado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroadopcion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
