# Generated by Django 4.2 on 2023-05-30 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_alter_perroadopcion_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroadopcion',
            name='fecha_adopcion',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
        migrations.AddField(
            model_name='perroadopcion',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date(2023, 5, 30)),
        ),
    ]
