# Generated by Django 4.2 on 2023-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0015_alter_perroadopcion_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroadopcion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
