# Generated by Django 4.2 on 2023-05-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='contacto',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
