# Generated by Django 4.2 on 2023-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0002_alter_cuidador_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='horario_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='horario_inicial',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='tiempo_con_veterinaria',
            field=models.DateField(auto_now_add=True),
        ),
    ]
