# Generated by Django 4.2 on 2023-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0003_alter_cuidador_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='contacto',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
