# Generated by Django 4.2 on 2023-06-08 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuidadores', '0004_alter_cuidador_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='solicitantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
