# Generated by Django 4.2 on 2023-06-11 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuidadores', '0005_cuidador_solicitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='solicitantes',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_contacto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='cuidadores.cuidador')),
            ],
        ),
    ]
