# Generated by Django 4.2 on 2023-06-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0006_alter_cuidador_solicitantes_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='solicitantes',
        ),
    ]
