# Generated by Django 4.2 on 2023-04-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_alter_perro_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clave',
        ),
    ]
