# Generated by Django 4.2 on 2023-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave',
            field=models.CharField(default=123456, max_length=12),
            preserve_default=False,
        ),
    ]
