# Generated by Django 4.2 on 2023-04-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
