# Generated by Django 4.2 on 2023-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
