# Generated by Django 4.2 on 2023-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
