# Generated by Django 4.2 on 2023-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
