# Generated by Django 4.2 on 2023-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_is_staff_alter_cliente_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
