# Generated by Django 4.2 on 2023-04-30 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_cliente_groups_cliente_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='color',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='perro',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 4, 30, 17, 0, 9, 219588, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perro',
            name='nombre',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='perro',
            name='peso',
            field=models.CharField(blank=True, default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'M'), ('HEMBRA', 'H'), ('-', 'Ns')], default='-', max_length=6),
        ),
    ]
