# Generated by Django 4.2 on 2023-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_perro_color_perro_fecha_nacimiento_perro_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='color',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='peso',
            field=models.CharField(blank=True, default='-', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
