# Generated by Django 4.2 on 2023-05-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_perro_color_alter_perro_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
