# Generated by Django 4.2 on 2023-07-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerroPerdido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(default='', max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA'), ('ns', 'NS')], max_length=6)),
                ('color', models.CharField(default='', max_length=20, null=True)),
                ('edad', models.CharField(default='', max_length=20, null=True)),
                ('peso', models.CharField(default='', max_length=5, null=True)),
                ('contacto', models.CharField(default='', max_length=50, null=True)),
                ('altura', models.CharField(default='', max_length=5, null=True)),
                ('raza', models.CharField(choices=[('mestizo', 'MESTIZO'), ('Siberian Husky', 'SIBERIAN HUSKY'), ('Beagle', 'BEAGLE'), ('Rottweiler', 'ROTTWEILER'), ('Bull Terrier', 'BULL TERRIER'), ('Bulldog Frances', 'BULLDOG FRANCES'), ('Boxer', 'BOXER'), ('Dogo Argentino', 'DOGO ARGENTINO'), ('Gran Danes', 'GRAN DANES'), ('Labrador', 'LABRADOR'), ('Galgo', 'GALGO'), ('Shiba Inu', 'AKITA INU'), ('Golden', 'GOLDEN'), ('Dalmata', 'DALMATA'), ('Chihuahua', 'CHIHUAHUA'), ('San Bernardo', 'SAN BERNARDO'), ('Doberman', 'DOBERMAN'), ('Pastor Aleman', 'PASTOR ALEMAN')], default='', max_length=20, null=True)),
                ('descripcion', models.CharField(default='', max_length=500, null=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('encontrado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_encontrado', models.DateField(blank=True, null=True)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicador_perro_perdido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
