# Generated by Django 4.2 on 2023-07-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perroperdido',
            name='encontrado',
        ),
        migrations.AddField(
            model_name='perroperdido',
            name='perdido',
            field=models.BooleanField(default=True),
        ),
    ]
