# Generated by Django 4.2 on 2023-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0002_remove_perroperdido_encontrado_perroperdido_perdido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroperdido',
            name='es_propio',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
            preserve_default=False,
        ),
    ]
