# Generated by Django 4.2 on 2023-07-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0003_perroperdido_es_propio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='es_propio',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
    ]
