# Generated by Django 4.2 on 2023-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_alter_perroperdido_es_propio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='es_propio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perroperdido',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
