# Generated by Django 4.2 on 2023-07-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0005_alter_perroperdido_es_propio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perroperdido',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='perroperdido',
            name='peso',
        ),
    ]
