# Generated by Django 4.2 on 2023-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0007_perroperdido_activo_alter_perroperdido_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroperdido',
            name='direccion',
            field=models.CharField(default='Casco Urbano', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perroperdido',
            name='zona',
            field=models.CharField(choices=[('Casco Urbano', 'Casco Urbano'), ('Villa Elvira', 'Villa Elvira'), ('Tolosa', 'Tolosa'), ('Ringuelet', 'Ringuelet'), ('Manuel B. Gonnet', 'Manuel B. Gonnet'), ('José Hernández', 'José Hernández'), ('Joaquín Gorina', 'Joaquín Gorina'), ('Los Hornos', 'Los Hornos'), ('San Carlos', 'San Carlos'), ('City Bell', 'City Bell'), ('Savoia', 'Savoia'), ('Altos de San Lorenzo', 'Altos de San Lorenzo'), ('Villa Elisa', 'Villa Elisa'), ('El Peligro', 'El Peligro'), ('Arturo Seguí', 'Arturo Seguí'), ('Melchor Romero', 'Melchor Romero'), ('Colonia Urquiza', 'Colonia Urquiza'), ('Abasto', 'Abasto'), ('Lisandro Olmos', 'Lisandro Olmos'), ('Ángel Etcheverry', 'Ángel Etcheverry'), ('Eduardo Arana', 'Eduardo Arana')], default='Casco Urbano', max_length=20),
        ),
    ]
