# Generated by Django 4.2 on 2023-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primer_login',
            field=models.BooleanField(default=True),
        ),
    ]
