# Generated by Django 4.2 on 2023-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=20, null=True)),
                ('color', models.CharField(default='', max_length=20, null=True)),
                ('raza', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'M'), ('HEMBRA', 'H'), ('-', 'Ns')], default='-', max_length=6)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.CharField(blank=True, default='', max_length=5, null=True)),
            ],
        ),
    ]
