# Generated by Django 4.2 on 2023-05-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
