# Generated by Django 4.2 on 2023-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_alter_perro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='color',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='peso',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
