# Generated by Django 4.2 on 2023-05-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra'), ('-', 'Ns')], default='-', max_length=6),
        ),
    ]
