# Generated by Django 4.2 on 2023-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_alter_perro_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA'), ('ns', 'NS')], max_length=6),
        ),
    ]
