# Generated by Django 4.2 on 2023-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0007_alter_perro_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
