# Generated by Django 4.2 on 2023-06-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0008_perro_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='responsable_activo',
            field=models.BooleanField(default=True),
        ),
    ]
