# Generated by Django 4.2 on 2023-05-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('motivo', models.CharField(choices=[('Vacunación', 'Vacunacion'), ('Castración', 'Castracion'), ('Consulta general', 'Consulta'), ('Consulta de urgencia', 'Urgencia'), ('Desparasitación', 'Desparasitacion')], default='Consulta general', max_length=20)),
                ('detalles', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_turnos', to=settings.AUTH_USER_MODEL)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros_turnos', to='perros.perro')),
            ],
        ),
    ]
