# Generated by Django 4.2 on 2023-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('vacunacion', 'Vacunación'), ('castracion', 'Castración'), ('consulta', 'Consulta general'), ('urgencia', 'Consulta de urgencia'), ('desparasitacion', 'Desparasitación')], max_length=20),
        ),
    ]
