# Generated by Django 4.2 on 2023-06-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0004_alter_perro_sexo'),
        ('turnos', '0007_alter_turno_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='turno',
            name='perro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros_turnos', to='perros.perro'),
        ),
    ]
