# Generated by Django 4.2 on 2023-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_remove_turno_cliente_alter_turno_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='detalles',
            field=models.CharField(default='Sin detalles.', max_length=50, null=True),
        ),
    ]
