# Generated by Django 4.2 on 2023-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_alter_turno_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='detalles',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
