# Generated by Django 4.2 on 2023-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_alter_turno_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='detalles',
            field=models.CharField(blank=True, default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, choices=[('vacunación antirrábica', 'Vacunación Antirrábica'), ('vacunación general', 'Vacunación General'), ('castración', 'Castración'), ('consulta', 'Consulta general'), ('desparasitación', 'Desparasitación')], max_length=25),
        ),
    ]
