# Generated by Django 4.2 on 2023-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_turno_detalles_alter_turno_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='detalles',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
