# Generated by Django 4.2 on 2023-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_turno_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('vacunacion_antirrabica', 'Vacunación Antirrábica'), ('vacunacion_general', 'Vacunación General'), ('castracion', 'Castración'), ('consulta', 'Consulta general'), ('urgencia', 'Consulta de urgencia'), ('desparasitacion', 'Desparasitación')], max_length=25),
        ),
    ]
