# Generated by Django 4.2 on 2023-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_alter_turno_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
