# Generated by Django 4.2 on 2023-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_alter_turno_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
