# Generated by Django 4.2 on 2023-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_turno_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='is_active',
        ),
        migrations.AddField(
            model_name='turno',
            name='asistido',
            field=models.BooleanField(default=False),
        ),
    ]
