# Generated by Django 4.2 on 2023-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_remove_turno_is_active_turno_asistido'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
