# Generated by Django 4.2 on 2023-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_turno_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, choices=[('vacunacion antirrabica', 'Vacunación Antirrábica'), ('vacunacion general', 'Vacunación General'), ('castracion', 'Castración'), ('consulta', 'Consulta general'), ('desparasitacion', 'Desparasitación')], max_length=25),
        ),
    ]
