# Generated by Django 4.2 on 2023-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_alter_turno_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, choices=[('vacunación antirrábica', 'Vacunación Antirrábica'), ('vacunación general', 'Vacunación General'), ('castración', 'Castración'), ('consulta', 'Consulta general'), ('desparasitación', 'Desparasitación')], max_length=25),
        ),
    ]
